apiVersion: v1
kind: Service
metadata:  
  labels:
    app: {{ template "name" . }}
    redis-operator.k8s.io/cluster-name: {{ template "clustername" . }}
  name: exporter-{{ template "name" . }}
spec:  
  ports:
  - name: exporter
    port: 9121
    protocol: TCP
    targetPort: 9121
  selector:
    app: {{ template "name" . }}
    redis-operator.k8s.io/cluster-name: {{ template "clustername" . }}
