{{- if .Values.esNode.ingress.enabled -}}
{{- $fullName := include "elasticsearch.esNode.fullname" . -}}
{{- $ingressPath := .Values.esNode.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.esNode.name }}"
    release: {{ .Release.Name }}
{{- with .Values.esNode.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- if and ( .Values.esNode.ingress.user ) ( .Values.esNode.ingress.password ) }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: '{{ include "elasticsearch.esNode.fullname" . }}-auth'
    nginx.ingress.kubernetes.io/auth-realm: "Authentication-Required"
{{- end }}
spec:
{{- if .Values.esNode.ingress.tls }}
  tls:
  {{- range .Values.esNode.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.esNode.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- end }}
{{- end }}
