{{- if .Values.esNode.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "elasticsearch.fullname" . }}
spec:
  accessModes:
{{ toYaml .Values.esNode.persistence.accessModes | indent 4 }}
{{- if .Values.esNode.persistence.storageClass }}
{{- if (eq "-" .Values.esNode.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.esNode.persistence.storageClass }}"
{{- end }}
{{- end }}
  resources:
    requests:
      storage: "{{ .Values.esNode.persistence.size }}"
    {{- if hasKey .Values.esNode.persistence "selector" }}
  selector:
{{ toYaml .Values.esNode.persistence.selector | indent 4 }}
    {{ end }}
{{- end -}}