{{- if .Values.serviceAccounts.esNode.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.esNode.name }}"
    release: {{ .Release.Name }}
  name: {{ template "elasticsearch.esNode.fullname" . }}
{{- end }}
